---
- hosts: 192.168.36.137
  become: true
  task: 
    - name: Install packages
      apt:
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service: 
        name: httpd
        state: started
        enable: True
    - name: Deploy static website
      copy:
        src: pom.xml
        dest: /var/www/html/
